# DOMAIN LEDGER
MARKER_ATTR = "1"
MARKER_SCHEMA = "2"
MARKER_CLAIM_DEF = "3"
MARKER_REVOC_DEF = "4"
MARKER_REVOC_REG_ENTRY = "5"
MARKER_REVOC_REG_ENTRY_ACCUM = "6"
MARKER_CONTEXT = "7"  # Rich Schema How is this used
MARKER_RS_SCHEMA = "8"
MARKER_RS_DID_DOC = "9"
MARKER_RS_CRED_DEF = "10"
MARKER_RS_MAPPING = "11"
MARKER_RS_ENCODING = "12"
MARKER_RS_PRES_DEF = "13"
LAST_SEQ_NO = "lsn"
VALUE = "val"
LAST_UPDATE_TIME = "lut"

# CONFIG LEDGER
MARKER_AUTH_RULE = "1"
